version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: justdrew2
      POSTGRES_DB: bootscoot
    ports:
      - "5432:5432"

  backend:
    build: ./java
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bootscoot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: justdrew2
    depends_on:
      - db

  frontend:
    build: ./react
    ports:
      - "5173:80"
    depends_on:
      - backend
